### ISSUE TITLE
Images/placeholder are broken

### ISSUE THREAD

**Issue by dulvui** [noi-techpark/webcomp-recipe#5]
In the WebComponentStore no images are shown.
On local machine placeholders are visible but when uploading to the store a broken image is shown.
Fixing issue #4 might fix this issue too.
@maximiliannocker

**Comment by Piiit** [comment]
@maximiliannocker The problem here is that our CDN does not support folders at the moment. So please flatten the "dist/img" folder into the "dist" folder, and adapt the code to that... Thx

I have added a pipeline step, that automatically updates the wcs-manifest.json to all files inside "dist", but only 1 level deep.

**Comment by Piiit** [comment]
@maximiliannocker I have also opened this issue inside your Kanban...

**Comment by SirCotare** [comment]
There should no longer be any dist files except the "webcomp-recipe.min.js" file. All images were tiny svg images anyway and are now bundled with the main script file.

**Comment by Piiit** [comment]
@SirCotare OK, checked that... I pushed a clean dist folder to the development branch now. You were right, there is no dist/img folder anymore, but other files still exist:
```
demo.html  webcomp-recipe.js  webcomp-recipe.js.map  webcomp-recipe.min.js  webcomp-recipe.min.js.map
```

@sseppi @SirCotare 
Is it correct, that we have always the same image above all titles? 
![Selection_047](https://user-images.githubusercontent.com/6096063/114197515-b8b26880-9952-11eb-8dcd-77998048de54.png)
